# Travis CI Configuration File

sudo: false

# Tell Travis CI we're using PHP
language: php

# PHP version used in first build configuration.
php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0

# WordPress version used in first build configuration.
env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=4.4 WP_MULTISITE=0
    - WP_VERSION=4.4 WP_MULTISITE=1
    - WP_VERSION=4.5 WP_MULTISITE=0
    - WP_VERSION=4.5 WP_MULTISITE=1
    - WP_VERSION=4.6 WP_MULTISITE=0
    - WP_VERSION=4.6 WP_MULTISITE=1
    - WP_VERSION=4.7 WP_MULTISITE=0
    - WP_VERSION=4.7 WP_MULTISITE=1

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - export PATH="$HOME/.composer/vendor/bin:$PATH" 
    - | 
      if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then 
        composer global require "phpunit/phpunit=5.7.*" 
      else 
        composer global require "phpunit/phpunit=4.8.*" 
      fi
    - phpunit --version

script: phpunit --coverage-clover=coverage.xml
